language: node_js
node_js: 12

install: npm install
cache:
  directories:
    - "node_modules"
 
services:
  - postgresql
  - redis-server

before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres
  - npm run migrate

scripts: npm test

after_success: 
  - npm run coverage
